#------------- PERSONA ------------
NACIONALIDADES = [
    ("AF", "Afganistán"),
    ("AL", "Albania"),
    ("DE", "Alemania"),
    ("AD", "Andorra"),
    ("AO", "Angola"),
    ("AI", "Anguila"),
    ("AQ", "Antártida"),
    # ("AG", "Antigua y Barbuda"),
    # ("AN", "Antillas Neerlandesas"),
    ("SA", "Arabia Saudita"),
    ("DZ", "Argelia"),
    ("AR", "Argentina"),
    ("AM", "Armenia"),
    ("AW", "Aruba"),
    ("AU", "Australia"),
    ("AT", "Austria"),
    ("AZ", "Azerbaiyán"),
    ("BS", "Bahamas"),
    ("BH", "Bahréin"),
    ("BD", "Bangladesh"),
    ("BB", "Barbados"),
    ("BE", "Bélgica"),
    ("BZ", "Belice"),
    ("BJ", "Benín"),
    ("BM", "Bermudas"),
    ("BY", "Bielorrusia"),
    ("MM", "Birmania"),
    ("BO", "Bolivia"),
    # ("BA", "Bosnia y Herzegovina"),
    ("BW", "Botsuana"),
    ("BR", "Brasil"),
    ("BN", "Brunéi"),
    ("BG", "Bulgaria"),
    ("BF", "Burkina Faso"),
    ("BI", "Burundi"),
    ("BT", "Bután"),
    ("CV", "Cabo Verde"),
    ("KH", "Camboya"),
    ("CM", "Camerún"),
    ("CA", "Canadá"),
    ("TD", "Chad"),
    ("CL", "Chile"),
    ("CN", "China"),
    ("CY", "Chipre"),
    # ("VA", "Ciudad del Vaticano"),
    ("CO", "Colombia"),
    ("KM", "Comoras"),
    ("CG", "Congo"),
    # ("CD", "Congo, República Democrática del"),
    ("KP", "Corea del Norte"),
    ("KR", "Corea del Sur"),
    ("CI", "Costa de Marfil"),
    ("CR", "Costa Rica"),
    ("HR", "Croacia"),
    ("CU", "Cuba"),
    ("DK", "Dinamarca"),
    ("DM", "Dominica"),
    ("EC", "Ecuador"),
    ("EG", "Egipto"),
    ("SV", "El Salvador"),
    ("AE", "Emiratos Árabes"),
    ("ER", "Eritrea"),
    ("SK", "Eslovaquia"),
    ("SI", "Eslovenia"),
    ("ES", "España"),
    ("US", "Estados Unidos"),
    ("EE", "Estonia"),
    ("ET", "Etiopía"),
    ("PH", "Filipinas"),
    ("FI", "Finlandia"),
    ("FJ", "Fiyi"),
    ("FR", "Francia"),
    ("GA", "Gabón"),
    ("GM", "Gambia"),
    ("GE", "Georgia"),
    ("GH", "Ghana"),
    ("GI", "Gibraltar"),
    ("GD", "Granada"),
    ("GR", "Grecia"),
    ("GL", "Groenlandia"),
    ("GP", "Guadalupe"),
    ("GU", "Guam"),
    ("GT", "Guatemala"),
    ("GY", "Guayana"),
    ("GF", "Guayana Francesa"),
    ("GN", "Guinea"),
    ("GQ", "Guinea Ecuatorial"),
    ("GW", "Guinea-Bisáu"),
    ("HT", "Haití"),
    ("HN", "Honduras"),
    ("HU", "Hungría"),
    ("IN", "India"),
    ("ID", "Indonesia"),
    ("IR", "Irán"),
    ("IQ", "Iraq"),
    ("IE", "Irlanda"),
    ("IS", "Islandia"),
    ("IL", "Israel"),
    ("IT", "Italia"),
    ("JM", "Jamaica"),
    ("JP", "Japón"),
    ("JO", "Jordania"),
    ("KZ", "Kazajistán"),
    ("KE", "Kenia"),
    ("KG", "Kirguistán"),
    ("KW", "Kuwait"),
    ("LA", "Laos"),
    ("LS", "Lesoto"),
    ("LV", "Letonia"),
    ("LB", "Líbano"),
    ("LR", "Liberia"),
    ("LY", "Libia"),
    ("LI", "Liechtenstein"),
    ("LT", "Lituania"),
    ("LU", "Luxemburgo"),
    ("MK", "Macedonia"),
    ("MG", "Madagascar"),
    ("MY", "Malasia"),
    ("MW", "Malaui"),
    ("MV", "Maldivas"),
    ("ML", "Malí"),
    ("MT", "Malta"),
    ("MA", "Marruecos"),
    ("MQ", "Martinica"),
    ("MU", "Mauricio"),
    ("MR", "Mauritania"),
    ("YT", "Mayotte"),
    ("MX", "México"),
    ("FM", "Micronesia"),
    ("MD", "Moldavia"),
    ("MC", "Mónaco"),
    ("MN", "Mongolia"),
    ("MS", "Montserrat"),
    ("MZ", "Mozambique"),
    ("NA", "Namibia"),
    ("NR", "Nauru"),
    ("NP", "Nepal"),
    ("NI", "Nicaragua"),
    ("NE", "Níger"),
    ("NG", "Nigeria"),
    ("NU", "Niue"),
    ("NF", "Norfolk"),
    ("NO", "Noruega"),
    ("NC", "Nueva Caledonia"),
    ("NZ", "Nueva Zelanda"),
    ("OM", "Omán"),
    ("NL", "Países Bajos"),
    ("PA", "Panamá"),
    ("PG", "Papúa Nueva Guinea"),
    ("PK", "Pakistán"),
    ("PY", "Paraguay"),
    ("PE", "Perú"),
    ("PN", "Pitcairn"),
    ("PF", "Polinesia Francesa"),
    ("PL", "Polonia"),
    ("PT", "Portugal"),
    ("PR", "Puerto Rico"),
    ("QA", "Qatar"),
    ("UK", "Reino Unido"),
    # ("CF", "República Centroafricana"),
    ("CZ", "República Checa"),
    ("DO", "República Dominicana"),
    ("RE", "Reunión"),
    ("RW", "Ruanda"),
    ("RO", "Rumania"),
    ("RU", "Rusia"),
    ("EH", "Sahara Occidental"),
    ("WS", "Samoa"),
    ("AS", "Samoa Americana"),
    # ("KN", "San Cristóbal y Nieves"),
    ("SM", "San Marino"),
    ("PM", "San Pedro y Miquelón"),
    # ("VC", "San Vicente y las Granadinas"),
    ("SH", "Santa Elena"),
    ("LC", "Santa Lucía"),
    ("ST", "Santo Tomé y Príncipe"),
    ("SN", "Senegal"),
    ("CS", "Serbia y Montenegro"),
    ("SC", "Seychelles"),
    ("SL", "Sierra Leona"),
    ("SG", "Singapur"),
    ("SY", "Siria"),
    ("SO", "Somalia"),
    ("LK", "Sri Lanka"),
    ("SZ", "Suazilandia"),
    ("ZA", "Sudáfrica"),
    ("SD", "Sudán"),
    ("SE", "Suecia"),
    ("CH", "Suiza"),
    ("SR", "Surinam"),
    # ("SJ", "Svalbard y Jan Mayen"),
    ("TH", "Tailandia"),
    ("TW", "Taiwán"),
    ("TZ", "Tanzania"),
    ("TJ", "Tayikistán"),
    # ("IO", "Territorio Británico del Océano Índico"),
    # ("TF", "Territorios Australes Franceses"),
    ("TL", "Timor Oriental"),
    ("TG", "Togo"),
    ("TK", "Tokelau"),
    ("TO", "Tonga"),
    ("TT", "Trinidad y Tobago"),
    ("TN", "Túnez"),
    ("TM", "Turkmenistán"),
    ("TR", "Turquía"),
    ("TV", "Tuvalu"),
    ("UA", "Ucrania"),
    ("UG", "Uganda"),
    ("UY", "Uruguay"),
    ("UZ", "Uzbekistán"),
    ("VU", "Vanuatu"),
    ("VE", "Venezuela"),
    ("VN", "Vietnam"),
    ("WF", "Wallis y Futuna"),
    ("YE", "Yemen"),
    ("DJ", "Yibuti"),
    ("ZM", "Zambia"),
    ("ZW", "Zimbabue"),
    ]

ESTADO_CIVIL = (
        (1, 'Soltero'),
        (2, 'Casado'),
        (3, 'Divorciado'),
        (4, 'Viudo/a'),
        (5, 'Separado/a'),
        (6, 'Convivencia')
    )

LOCALIDADES_CHUBUT = [
        ('', '--------'),  # Opción vacía
        ("RAWSON", "Rawson"),
        ("PUERTO MADRYN", "Puerto Madryn"),
        ("GAIMAN", "Gaiman"),
        ("TRELEW", "Trelew"),
    ]


MAX_LENGTHS = {
        'dni': 8,
        'cuil': 11,
        'nombre': 30,
        'apellido': 30,
        'celular': 10,
        'direccion': 50,
        'nacionalidad': 2,
        'mail': 50,
    }

#------------- AFILIADO ------------
AFILIADO_ESTADO = (
        (1, "Pendiente"),
        (2, "Activo"),
        (3, "Inactivo"),
        (4, "Dado de baja"),
        (5, "Moroso"),
    )

TIPOS_RELACION_FAMILIAR = (
        (1, "Conyugue"),
        (2, "Hijo/a"),
    )

#------------- AULA ------------
TIPO_AULA = [
        ('normal', 'Normal'),
        ('computacion', 'Computación'),
]

AREAS = [
        (0, "Capacitación"),
        (1, "Cultura"),
        (2, "Gimnasio Saludable"), 
]

DIAS_SEMANA_CHOICES = [
        (0, 'Lunes'),
        (1, 'Martes'),
        (2, 'Miércoles'),
        (3, 'Jueves'),
        (4, 'Viernes'),
        # (5, 'Sábado'),
    ]

PERIODO_PAGO=(
        (1, 'mes'),
        (2, 'clase'),
    )

ESTADO_DICTADO=(
        (1, 'No iniciado'),
        (2, 'En curso'),
        (3, 'Finalizado'),
)

MONTH_CHOICES = [
        (1, 'Enero'),
        (2, 'Febrero'),
        (3, 'Marzo'),
        (4, 'Abril'),
        (5, 'Mayo'),
        (6, 'Junio'),
        (7, 'Julio'),
        (8, 'Agosto'),
        (9, 'Septiembre'),
        (10, 'Octubre'),
        (11, 'Noviembre'),
        (12, 'Diciembre'),
    ]
